# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ai_service_pb2 as ai__service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ai_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIServiceStub(object):
    """--- AI Service Definition ---

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TranscribeAudio = channel.unary_unary(
                '/aiservice.AIService/TranscribeAudio',
                request_serializer=ai__service__pb2.TranscribeAudioRequest.SerializeToString,
                response_deserializer=ai__service__pb2.TranscribeAudioResponse.FromString,
                _registered_method=True)
        self.FormatCaptions = channel.unary_unary(
                '/aiservice.AIService/FormatCaptions',
                request_serializer=ai__service__pb2.FormatCaptionsRequest.SerializeToString,
                response_deserializer=ai__service__pb2.FormatCaptionsResponse.FromString,
                _registered_method=True)


class AIServiceServicer(object):
    """--- AI Service Definition ---

    """

    def TranscribeAudio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FormatCaptions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TranscribeAudio': grpc.unary_unary_rpc_method_handler(
                    servicer.TranscribeAudio,
                    request_deserializer=ai__service__pb2.TranscribeAudioRequest.FromString,
                    response_serializer=ai__service__pb2.TranscribeAudioResponse.SerializeToString,
            ),
            'FormatCaptions': grpc.unary_unary_rpc_method_handler(
                    servicer.FormatCaptions,
                    request_deserializer=ai__service__pb2.FormatCaptionsRequest.FromString,
                    response_serializer=ai__service__pb2.FormatCaptionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aiservice.AIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aiservice.AIService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIService(object):
    """--- AI Service Definition ---

    """

    @staticmethod
    def TranscribeAudio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiservice.AIService/TranscribeAudio',
            ai__service__pb2.TranscribeAudioRequest.SerializeToString,
            ai__service__pb2.TranscribeAudioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FormatCaptions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aiservice.AIService/FormatCaptions',
            ai__service__pb2.FormatCaptionsRequest.SerializeToString,
            ai__service__pb2.FormatCaptionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
