basePath: /api/v1
definitions:
  handlers.CreateProjectRequest:
    properties:
      description:
        type: string
      name:
        type: string
      thumbnail_url:
        type: string
    required:
    - name
    type: object
  handlers.ErrorResponse:
    properties:
      message:
        type: string
      status:
        type: string
    type: object
  handlers.ProjectListSuccessResponse:
    properties:
      data:
        items:
          $ref: '#/definitions/models.Project'
        type: array
      message:
        type: string
      status:
        type: string
    type: object
  handlers.ProjectSuccessResponse:
    properties:
      data:
        $ref: '#/definitions/models.Project'
      message:
        type: string
      status:
        type: string
    type: object
  models.Project:
    properties:
      created_at:
        type: string
      description:
        description: Use a pointer for nullable TEXT fields
        type: string
      id:
        type: string
      name:
        type: string
      thumbnail_url:
        description: Use a pointer for nullable TEXT fields
        type: string
      updated_at:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@example.com
    name: API Support
    url: http://example.com/support
  description: This is the API gateway for the OpusClip video processing service.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://example.com/terms/
  title: OpusClip API Gateway
  version: "1.0"
paths:
  /projects:
    get:
      consumes:
      - application/json
      description: Retrieves a list of all projects from the database.
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved list of projects
          schema:
            $ref: '#/definitions/handlers.ProjectListSuccessResponse'
        "500":
          description: Internal server error if projects cannot be retrieved
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: List all projects
      tags:
      - projects
    post:
      consumes:
      - application/json
      description: Creates a new project with the provided name and optional description
        and thumbnail URL.
      parameters:
      - description: Project to create
        in: body
        name: project
        required: true
        schema:
          $ref: '#/definitions/handlers.CreateProjectRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Project created successfully
          schema:
            $ref: '#/definitions/handlers.ProjectSuccessResponse'
        "400":
          description: Bad request if input is invalid (e.g., missing name)
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal server error if project creation fails
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Create a new project
      tags:
      - projects
schemes:
- http
- https
swagger: "2.0"
