// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: ai_service.proto

package aiservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TranscriptSegment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	StartTime     float64                `protobuf:"fixed64,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       float64                `protobuf:"fixed64,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscriptSegment) Reset() {
	*x = TranscriptSegment{}
	mi := &file_ai_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscriptSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscriptSegment) ProtoMessage() {}

func (x *TranscriptSegment) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscriptSegment.ProtoReflect.Descriptor instead.
func (*TranscriptSegment) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{0}
}

func (x *TranscriptSegment) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TranscriptSegment) GetStartTime() float64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *TranscriptSegment) GetEndTime() float64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type Highlight struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	StartTime     float64                `protobuf:"fixed64,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       float64                `protobuf:"fixed64,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Score         float32                `protobuf:"fixed32,4,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Highlight) Reset() {
	*x = Highlight{}
	mi := &file_ai_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Highlight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Highlight) ProtoMessage() {}

func (x *Highlight) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Highlight.ProtoReflect.Descriptor instead.
func (*Highlight) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{1}
}

func (x *Highlight) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Highlight) GetStartTime() float64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Highlight) GetEndTime() float64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *Highlight) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type TranscribeAudioRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AudioData        []byte                 `protobuf:"bytes,1,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"`                      // Raw audio bytes
	OriginalFilename string                 `protobuf:"bytes,2,opt,name=original_filename,json=originalFilename,proto3" json:"original_filename,omitempty"` // e.g., "test.mp3"
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TranscribeAudioRequest) Reset() {
	*x = TranscribeAudioRequest{}
	mi := &file_ai_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscribeAudioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscribeAudioRequest) ProtoMessage() {}

func (x *TranscribeAudioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscribeAudioRequest.ProtoReflect.Descriptor instead.
func (*TranscribeAudioRequest) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{2}
}

func (x *TranscribeAudioRequest) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

func (x *TranscribeAudioRequest) GetOriginalFilename() string {
	if x != nil {
		return x.OriginalFilename
	}
	return ""
}

type TranscribeAudioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Segments      []*TranscriptSegment   `protobuf:"bytes,2,rep,name=segments,proto3" json:"segments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscribeAudioResponse) Reset() {
	*x = TranscribeAudioResponse{}
	mi := &file_ai_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscribeAudioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscribeAudioResponse) ProtoMessage() {}

func (x *TranscribeAudioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscribeAudioResponse.ProtoReflect.Descriptor instead.
func (*TranscribeAudioResponse) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{3}
}

func (x *TranscribeAudioResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *TranscribeAudioResponse) GetSegments() []*TranscriptSegment {
	if x != nil {
		return x.Segments
	}
	return nil
}

type DetectHighlightsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Segments      []*TranscriptSegment   `protobuf:"bytes,1,rep,name=segments,proto3" json:"segments,omitempty"` // int32 num_highlights = 2; // Optional: to limit results
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectHighlightsRequest) Reset() {
	*x = DetectHighlightsRequest{}
	mi := &file_ai_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectHighlightsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectHighlightsRequest) ProtoMessage() {}

func (x *DetectHighlightsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectHighlightsRequest.ProtoReflect.Descriptor instead.
func (*DetectHighlightsRequest) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{4}
}

func (x *DetectHighlightsRequest) GetSegments() []*TranscriptSegment {
	if x != nil {
		return x.Segments
	}
	return nil
}

type DetectHighlightsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Highlights    []*Highlight           `protobuf:"bytes,1,rep,name=highlights,proto3" json:"highlights,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectHighlightsResponse) Reset() {
	*x = DetectHighlightsResponse{}
	mi := &file_ai_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectHighlightsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectHighlightsResponse) ProtoMessage() {}

func (x *DetectHighlightsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectHighlightsResponse.ProtoReflect.Descriptor instead.
func (*DetectHighlightsResponse) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{5}
}

func (x *DetectHighlightsResponse) GetHighlights() []*Highlight {
	if x != nil {
		return x.Highlights
	}
	return nil
}

type FormatCaptionsRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Segments           []*TranscriptSegment   `protobuf:"bytes,1,rep,name=segments,proto3" json:"segments,omitempty"`
	MaxCharsPerLine    int32                  `protobuf:"varint,2,opt,name=max_chars_per_line,json=maxCharsPerLine,proto3" json:"max_chars_per_line,omitempty"`
	MaxLinesPerCaption int32                  `protobuf:"varint,3,opt,name=max_lines_per_caption,json=maxLinesPerCaption,proto3" json:"max_lines_per_caption,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *FormatCaptionsRequest) Reset() {
	*x = FormatCaptionsRequest{}
	mi := &file_ai_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormatCaptionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormatCaptionsRequest) ProtoMessage() {}

func (x *FormatCaptionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormatCaptionsRequest.ProtoReflect.Descriptor instead.
func (*FormatCaptionsRequest) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{6}
}

func (x *FormatCaptionsRequest) GetSegments() []*TranscriptSegment {
	if x != nil {
		return x.Segments
	}
	return nil
}

func (x *FormatCaptionsRequest) GetMaxCharsPerLine() int32 {
	if x != nil {
		return x.MaxCharsPerLine
	}
	return 0
}

func (x *FormatCaptionsRequest) GetMaxLinesPerCaption() int32 {
	if x != nil {
		return x.MaxLinesPerCaption
	}
	return 0
}

type FormatCaptionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SrtContent    string                 `protobuf:"bytes,1,opt,name=srt_content,json=srtContent,proto3" json:"srt_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FormatCaptionsResponse) Reset() {
	*x = FormatCaptionsResponse{}
	mi := &file_ai_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FormatCaptionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormatCaptionsResponse) ProtoMessage() {}

func (x *FormatCaptionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormatCaptionsResponse.ProtoReflect.Descriptor instead.
func (*FormatCaptionsResponse) Descriptor() ([]byte, []int) {
	return file_ai_service_proto_rawDescGZIP(), []int{7}
}

func (x *FormatCaptionsResponse) GetSrtContent() string {
	if x != nil {
		return x.SrtContent
	}
	return ""
}

var File_ai_service_proto protoreflect.FileDescriptor

const file_ai_service_proto_rawDesc = "" +
	"\n" +
	"\x10ai_service.proto\x12\taiservice\"a\n" +
	"\x11TranscriptSegment\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\x01R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\x01R\aendTime\"o\n" +
	"\tHighlight\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\x01R\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\x01R\aendTime\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x02R\x05score\"d\n" +
	"\x16TranscribeAudioRequest\x12\x1d\n" +
	"\n" +
	"audio_data\x18\x01 \x01(\fR\taudioData\x12+\n" +
	"\x11original_filename\x18\x02 \x01(\tR\x10originalFilename\"o\n" +
	"\x17TranscribeAudioResponse\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x128\n" +
	"\bsegments\x18\x02 \x03(\v2\x1c.aiservice.TranscriptSegmentR\bsegments\"S\n" +
	"\x17DetectHighlightsRequest\x128\n" +
	"\bsegments\x18\x01 \x03(\v2\x1c.aiservice.TranscriptSegmentR\bsegments\"P\n" +
	"\x18DetectHighlightsResponse\x124\n" +
	"\n" +
	"highlights\x18\x01 \x03(\v2\x14.aiservice.HighlightR\n" +
	"highlights\"\xb1\x01\n" +
	"\x15FormatCaptionsRequest\x128\n" +
	"\bsegments\x18\x01 \x03(\v2\x1c.aiservice.TranscriptSegmentR\bsegments\x12+\n" +
	"\x12max_chars_per_line\x18\x02 \x01(\x05R\x0fmaxCharsPerLine\x121\n" +
	"\x15max_lines_per_caption\x18\x03 \x01(\x05R\x12maxLinesPerCaption\"9\n" +
	"\x16FormatCaptionsResponse\x12\x1f\n" +
	"\vsrt_content\x18\x01 \x01(\tR\n" +
	"srtContent2\x99\x02\n" +
	"\tAIService\x12X\n" +
	"\x0fTranscribeAudio\x12!.aiservice.TranscribeAudioRequest\x1a\".aiservice.TranscribeAudioResponse\x12[\n" +
	"\x10DetectHighlights\x12\".aiservice.DetectHighlightsRequest\x1a#.aiservice.DetectHighlightsResponse\x12U\n" +
	"\x0eFormatCaptions\x12 .aiservice.FormatCaptionsRequest\x1a!.aiservice.FormatCaptionsResponseB)Z'./internal/goclient/aiservice;aiserviceb\x06proto3"

var (
	file_ai_service_proto_rawDescOnce sync.Once
	file_ai_service_proto_rawDescData []byte
)

func file_ai_service_proto_rawDescGZIP() []byte {
	file_ai_service_proto_rawDescOnce.Do(func() {
		file_ai_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_service_proto_rawDesc), len(file_ai_service_proto_rawDesc)))
	})
	return file_ai_service_proto_rawDescData
}

var file_ai_service_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_ai_service_proto_goTypes = []any{
	(*TranscriptSegment)(nil),        // 0: aiservice.TranscriptSegment
	(*Highlight)(nil),                // 1: aiservice.Highlight
	(*TranscribeAudioRequest)(nil),   // 2: aiservice.TranscribeAudioRequest
	(*TranscribeAudioResponse)(nil),  // 3: aiservice.TranscribeAudioResponse
	(*DetectHighlightsRequest)(nil),  // 4: aiservice.DetectHighlightsRequest
	(*DetectHighlightsResponse)(nil), // 5: aiservice.DetectHighlightsResponse
	(*FormatCaptionsRequest)(nil),    // 6: aiservice.FormatCaptionsRequest
	(*FormatCaptionsResponse)(nil),   // 7: aiservice.FormatCaptionsResponse
}
var file_ai_service_proto_depIdxs = []int32{
	0, // 0: aiservice.TranscribeAudioResponse.segments:type_name -> aiservice.TranscriptSegment
	0, // 1: aiservice.DetectHighlightsRequest.segments:type_name -> aiservice.TranscriptSegment
	1, // 2: aiservice.DetectHighlightsResponse.highlights:type_name -> aiservice.Highlight
	0, // 3: aiservice.FormatCaptionsRequest.segments:type_name -> aiservice.TranscriptSegment
	2, // 4: aiservice.AIService.TranscribeAudio:input_type -> aiservice.TranscribeAudioRequest
	4, // 5: aiservice.AIService.DetectHighlights:input_type -> aiservice.DetectHighlightsRequest
	6, // 6: aiservice.AIService.FormatCaptions:input_type -> aiservice.FormatCaptionsRequest
	3, // 7: aiservice.AIService.TranscribeAudio:output_type -> aiservice.TranscribeAudioResponse
	5, // 8: aiservice.AIService.DetectHighlights:output_type -> aiservice.DetectHighlightsResponse
	7, // 9: aiservice.AIService.FormatCaptions:output_type -> aiservice.FormatCaptionsResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_ai_service_proto_init() }
func file_ai_service_proto_init() {
	if File_ai_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_service_proto_rawDesc), len(file_ai_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_service_proto_goTypes,
		DependencyIndexes: file_ai_service_proto_depIdxs,
		MessageInfos:      file_ai_service_proto_msgTypes,
	}.Build()
	File_ai_service_proto = out.File
	file_ai_service_proto_goTypes = nil
	file_ai_service_proto_depIdxs = nil
}
